version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "terraform"
    directory: "/terraform/modules/terraform-proxmox-ec2"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "terraform"
    directory: "/terraform/modules/terraform-proxmox-pke"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "terraform"
    directory: "/terraform/modules/terraform-proxmox-rds"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
