# This file is managed by Flux and will be updated during bootstrap.
# To bootstrap Flux, run:
#   flux bootstrap github \
#     --owner=<your-github-username> \
#     --repository=proxmox-homelab \
#     --branch=main \
#     --path=kubernetes/clusters/homelab \
#     --personal
#
# Or for HTTPS with token:
#   flux bootstrap github \
#     --token-auth \
#     --owner=<your-github-username> \
#     --repository=proxmox-homelab \
#     --branch=main \
#     --path=kubernetes/clusters/homelab \
#     --personal
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  # TODO: Update this URL after running 'flux bootstrap' or manually set your repo URL
  # For SSH: ssh://git@github.com/<your-username>/proxmox-homelab.git
  # For HTTPS: https://github.com/<your-username>/proxmox-homelab.git
  url: ssh://git@github.com/OWNER/proxmox-homelab.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/clusters/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Decrypt secrets using SOPS (optional - uncomment if using SOPS)
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-age
